const ContenidoInicio = () => {
  return (
    <div className="content">
      <div className="container mw-60 pd-tb-30">
        <h1>Bienvenido a nuestra empresa Zapaticos SAS</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit cras, cursus orci urna rhoncus mattis posuere non ullamcorper libero, torquent dignissim dictumst ligula luctus nec nam. Fusce tellus libero donec mi turpis tempus sociis convallis ultrices pharetra, eget senectus habitasse egestas eleifend mattis risus placerat eu gravida, varius lacus commodo proin ultricies congue ridiculus litora consequat. Natoque tristique non erat ridiculus rhoncus maecenas dui, mollis est eleifend facilisis fames duis iaculis ligula, pharetra a quisque senectus dictum montes.<br/>Condimentum blandit dapibus quam semper vehicula lobortis volutpat imperdiet, mus ut leo dignissim senectus litora duis porttitor urna, faucibus sem vel nisl quisque sagittis maecenas. Parturient habitant nullam eros cubilia venenatis velit semper ornare platea bibendum auctor vestibulum, porta vel tempor lacinia per nostra risus cum ad taciti sociis, tellus feugiat egestas suscipit facilisi varius duis pulvinar curae primis vitae. Sociosqu sodales quisque litora mollis ante nunc nullam, urna at non phasellus ridiculus torquent est vivamus, suscipit varius nisl tempor imperdiet accumsan.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit cras, cursus orci urna rhoncus mattis posuere non ullamcorper libero, torquent dignissim dictumst ligula luctus nec nam. Fusce tellus libero donec mi turpis tempus sociis convallis ultrices pharetra, eget senectus habitasse egestas eleifend mattis risus placerat eu gravida, varius lacus commodo proin ultricies congue ridiculus litora consequat. Natoque tristique non erat ridiculus rhoncus maecenas dui, mollis est eleifend facilisis fames duis iaculis ligula, pharetra a quisque senectus dictum montes.<br/>Condimentum blandit dapibus quam semper vehicula lobortis volutpat imperdiet, mus ut leo dignissim senectus litora duis porttitor urna, faucibus sem vel nisl quisque sagittis maecenas. Parturient habitant nullam eros cubilia venenatis velit semper ornare platea bibendum auctor vestibulum, porta vel tempor lacinia per nostra risus cum ad taciti sociis, tellus feugiat egestas suscipit facilisi varius duis pulvinar curae primis vitae. Sociosqu sodales quisque litora mollis ante nunc nullam, urna at non phasellus ridiculus torquent est vivamus, suscipit varius nisl tempor imperdiet accumsan.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipiscing elit cras, cursus orci urna rhoncus mattis posuere non ullamcorper libero, torquent dignissim dictumst ligula luctus nec nam. Fusce tellus libero donec mi turpis tempus sociis convallis ultrices pharetra, eget senectus habitasse egestas eleifend mattis risus placerat eu gravida, varius lacus commodo proin ultricies congue ridiculus litora consequat. Natoque tristique non erat ridiculus rhoncus maecenas dui, mollis est eleifend facilisis fames duis iaculis ligula, pharetra a quisque senectus dictum montes.<br/>Condimentum blandit dapibus quam semper vehicula lobortis volutpat imperdiet, mus ut leo dignissim senectus litora duis porttitor urna, faucibus sem vel nisl quisque sagittis maecenas. Parturient habitant nullam eros cubilia venenatis velit semper ornare platea bibendum auctor vestibulum, porta vel tempor lacinia per nostra risus cum ad taciti sociis, tellus feugiat egestas suscipit facilisi varius duis pulvinar curae primis vitae. Sociosqu sodales quisque litora mollis ante nunc nullam, urna at non phasellus ridiculus torquent est vivamus, suscipit varius nisl tempor imperdiet accumsan.</p>
        </div>
    </div>
  );
}

export default ContenidoInicio;
